function out = funGetNmbrStdByDept(sDepartment, sStart, sEnd)
    % Example: funGetNmbrStdByDept('Mathematics', '2014.66', '2019.33')
    sSQL = ['select count(distinct IDENTIFIER) from OIR '... 
        ' where SHRTCKN_SUBJ_CODE in ' ...
        '(select SUBJECT from DEPT where DEPARTMENT=''' sDepartment ...
        ''') and DEPARTMENT <> ''NA'' '...
        'and CURRENTTERM >= ' sStart ' and CURRENTTERM <= ' sEnd];
    out = funQuery2Matrix(sSQL); 
end
